apiVersion: v1
kind: ConfigMap
metadata:
  name: statics-html
data:
  statics.html: |-
{{ .Files.Get "statics.html" | indent 4}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-conf
data:
  default.conf: |-
{{ .Files.Get "default.conf" | indent 4}}